language: python
python:
- '3.7'
install:
  - pip3 install pipenv pycodestyle
  - pipenv install --system --deploy
before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
script:
  - pycodestyle . --max-line-length=80 --ignore=E402,W503
  - PYTHONPATH=. pipenv run pytest -s
